version: "3.8"

services:
  api:
    build:
      context: .
      args:
        BUILD_PROFILE: prod
    environment:
      - MODEL_PROFILE=prod
      - ADAPTER_PATH=app/network_optimizer
      - MODEL_CACHE=/app/hf_models/cache
    # Enable one of the following when running on a GPU host:
    # gpus: all
    # OR (Swarm-style; not used in regular compose)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    ports:
      - "8000:8000"